### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Pdzly** [brandly/Lax#107]
Hi,

i would have a question is there a way to host such a server for "Lax"?

Because i didn´t found anything for a server or so.

**Comment by brandly** [comment]
Hey, this project doesn't have any server. It's just a client application that connects to existing IRC servers.

IRC is an open protocol, so you _could_ run your own server. I often run [this one](https://ngircd.barton.de/) on my local computer and connect to it, just for developing this app. Otherwise, I connect to `chat.freenode.net` to actually talk to people.

Hope that answers your question!
